import React,{useEffect,useRef,useState} from 'react';
import {friendlyError} from '../../presenter.mjs';
export function PlatformBodyForm({api,workspace,intake,inventory,setPlanPreview,setPlanPayload,setMessage}) {
  const [selection,setSelection]=useState('__new__'),[id,setId]=useState(''),[confirmed,setConfirmed]=useState(false),[fields,setFields]=useState({}),[displayName,setDisplayName]=useState(''),[mode,setMode]=useState('manual-native'),[args,setArgs]=useState('{client-descriptor}'),[identity,setIdentity]=useState('architecture-json-cli-client'),[error,setError]=useState(''),[working,setWorking]=useState(false),[result,setResult]=useState(null),[snapshot,setSnapshot]=useState(null);const serial=useRef(0),platformId=selection==='__new__'?id:selection;
  useEffect(()=>{const current=++serial.current;setSnapshot(null);setResult(null);if(!/^[a-z][a-z0-9-]{1,30}$/.test(platformId))return;api.readOnboardingConfig({workspaceRoot:workspace,platformId}).then(value=>{if(current!==serial.current)return;setFields(value.fields);setDisplayName(value.fields.displayName || platformId);setSnapshot(value);setError('');}).catch(error=>{if(current===serial.current)setError(friendlyError(error));});return ()=>{serial.current++;};},[api,workspace,platformId]);
  const act=async action=>{setWorking(true);setError('');try{const value=await action();if(value?.schema==='architecture-manager-plan/v1'){setPlanPreview(value);setPlanPayload(null);setMessage('平台本体接入计划已生成。配置和目录登记会明确保持待认证；安置不会启动客户端。');}else setResult(value);}catch(error){setError(friendlyError(error));}finally{setWorking(false);}};
  const pick=async key=>{const path=await api.selectOnboardingFile();if(path)setFields(previous=>({...previous,[key]:path}));else setError('已取消选择。');};
  return <section className="panel"><div className="panel-title"><span>平台本体与原生入口</span><span className="muted">本体、桥接服务、原生客户端与能力地板分别验证</span></div>
    <div className="wizard-grid"><div className="wizard-field"><label>平台</label><select value={selection} onChange={event=>setSelection(event.target.value)}><option value="__new__">创建独立平台</option>{inventory?.platforms?.map(row=><option key={row.id} value={row.id}>{row.id}</option>)}</select></div>{selection==='__new__' && <div className="wizard-field"><label>新平台 ID</label><input value={id} onChange={event=>setId(event.target.value.toLowerCase())} placeholder="my-client" /></div>}<div className="wizard-field"><label>显示名称</label><input value={displayName} onChange={event=>setDisplayName(event.target.value)} /></div></div>
    {selection==='__new__' && <label><input type="checkbox" checked={confirmed} onChange={event=>setConfirmed(event.target.checked)} />允许创建这个一级平台目录，并登记到架构说明中。</label>}
    <div className="wizard-field"><label>准备架构服务的 Python 解释器</label><input value={fields.pythonExecutable || ''} onChange={event=>setFields(previous=>({...previous,pythonExecutable:event.target.value}))} /><div className="git-actions"><button className="small-button" onClick={()=>pick('pythonExecutable')}>选择解释器</button><button className="small-button" disabled={working || !fields.pythonExecutable} onClick={()=>act(async()=>{const value=await api.detectOnboardingRuntime({pythonExecutable:fields.pythonExecutable});if(value.python?.executable)setFields(previous=>({...previous,pythonExecutable:value.python.executable}));return value;})}>检测所选解释器与 WSL</button></div></div>
    {snapshot?.performanceRecommendation && <button className="small-button" onClick={()=>setFields(previous=>({...previous,...snapshot.performanceRecommendation}))}>选择已发布的提速组合</button>}
    <div className="wizard-field"><label>本体提供什么接口</label><select value={mode} onChange={event=>setMode(event.target.value)}><option value="manual-native">GUI／接口未明确：安置本体，原生接线保持待完成</option><option value="json-cli">已实现架构 JSON stdin/stdout 协议的 CLI 客户端</option></select></div>
    {mode==='json-cli' && <details open><summary>明确的客户端启动配置</summary><p>客户端必须经架构服务返回随机挑战回执。普通软件的“--version”或仅能启动窗口不能代替此接口。</p><div className="wizard-field"><label>入口参数（每行一项，按原样传递）</label><textarea rows={4} value={args} onChange={event=>setArgs(event.target.value)} /><small>可使用 {'{client-body}'}、{'{client-descriptor}'}、{'{mcp-registration}'}、{'{runner-config}'}；预览会显示实际路径。</small></div><div className="wizard-field"><label>客户端回执身份</label><input value={identity} onChange={event=>setIdentity(event.target.value)} /></div><div className="wizard-field"><label>非 Python 脚本需要的 Node／Java 等程序（可留空）</label><input value={fields.clientRuntimeExecutable || ''} onChange={event=>setFields(previous=>({...previous,clientRuntimeExecutable:event.target.value}))} /><button className="small-button" onClick={()=>pick('clientRuntimeExecutable')}>选择运行程序</button></div></details>}
    <div className="git-actions"><button className="primary-small" disabled={working || !snapshot || !fields.pythonExecutable || selection==='__new__' && !confirmed} onClick={()=>act(()=>api.previewPlatformBody({intake,platformId,displayName,fields,confirmed,clientMode:mode,clientArgs:mode==='json-cli'?args.split(/\r?\n/).filter(Boolean):[],clientIdentity:identity}))}>预览本体接入</button><button className="small-button" disabled={working || !platformId} onClick={()=>act(()=>api.probeOnboardingClient({workspaceRoot:workspace,platformId}))}>测试已接入的真实客户端</button></div>
    {error && <div className="scan-result warning" role="alert">{error}</div>}
    {result && <div className={'scan-result '+(result.status==='passed'?'clean':'warning')}>{result.importedClientVerified?'所选本体的真实 CLI 连接已通过；还需能力地板和首次认证。':result.status==='passed'?'架构服务回环已通过；未据此声称厂商客户端已接线。':result.issues?.join('；') || result.status}<div className="path-line">{result.evidencePath || ''}</div></div>}
    <p>本体安置后，请到「平台与接入」选择这个平台，准备独立环境并运行接入／继续。缺原生接口、系统组件或登录时保持明确待完成状态；管理台不会要求 AI 会话手改配置，也不会据此刷绿。</p>
  </section>;
}
