import React,{useEffect,useState} from 'react';
import {friendlyError} from '../../presenter.mjs';
const newAction=()=>({name:'',args:'',parameters:[],sideEffects:'none',filesystem:'read',network:'none',probeReadOnly:false});
export function SoftwareBodyForm({api,workspace,platformId,intake,setMessage,setPlanPreview,setPlanPayload}) {
  const [id,setId]=useState(''),[displayName,setDisplayName]=useState(''),[upstream,setUpstream]=useState(''),[version,setVersion]=useState(''),[mode,setMode]=useState('cli'),[runtime,setRuntime]=useState(''),[versionArgs,setVersionArgs]=useState('--version'),[launchArgs,setLaunchArgs]=useState(''),[actions,setActions]=useState([]),[placement,setPlacement]=useState(null),[working,setWorking]=useState(false),[error,setError]=useState(''),[result,setResult]=useState(null);
  useEffect(()=>{let active=true;setPlacement(null);if(platformId && id)api.listRuntimeBodies({workspaceRoot:workspace,platformId}).then(rows=>{if(active){const previous=rows.findLast(row=>row.plan.target.resourceId===id && row.plan.payload.intake.sourceFingerprint===intake.sourceFingerprint && row.plan.payload.intake.selectedEntry===intake.selectedEntry);if(previous)setPlacement(previous.plan);}}).catch(error=>{if(active)setError(friendlyError(error));});return ()=>{active=false;};},[api,workspace,platformId,id,intake.sourceFingerprint,intake.selectedEntry]);
  const plan=async action=>{setWorking(true);setError('');try{const value=await action();setPlanPreview(value);setPlanPayload(null);setMessage('请核对软件计划并确认执行。版本询问、功能测试和会话状态各自记录。');}catch(error){setError(friendlyError(error));}finally{setWorking(false);}};
  const update=(index,patch)=>setActions(rows=>rows.map((row,i)=>i===index?{...row,...patch}:row));
  const serialize=()=>actions.map(row=>({...row,args:row.args.split(/\r?\n/).filter(Boolean),testArguments:Object.fromEntries(row.parameters.filter(parameter=>parameter.testValue!=='').map(parameter=>[parameter.name,parameter.type==='integer'?Number(parameter.testValue):parameter.type==='boolean'?parameter.testValue==='true':parameter.testValue]))}));
  const relay=operation=>plan(()=>api.previewSoftwareCommand({workspaceRoot:workspace,platformId,softwareId:id,operation}));
  return <section className="panel"><div className="panel-title"><span>软件本体、功能与会话</span><span className="muted">安置 → 声明并测试 → 发布和绑定</span></div>
    <div className="wizard-grid"><div className="wizard-field"><label>软件 ID（更新使用同一个 ID）</label><input value={id} onChange={event=>{setId(event.target.value.toLowerCase());setPlacement(null);}} placeholder="my-software" /></div><div className="wizard-field"><label>显示名称</label><input value={displayName} onChange={event=>setDisplayName(event.target.value)} /></div><div className="wizard-field"><label>本体版本（CLI 查询必须包含此值）</label><input value={upstream} onChange={event=>setUpstream(event.target.value)} /></div><div className="wizard-field"><label>配方版本（留空自动递增）</label><input value={version} onChange={event=>setVersion(event.target.value)} placeholder="1.0.0" /></div></div>
    <p>普通 CLI 与 GUI 会话使用通用连接器，不必逐个编写 MCP。安装包仅安置，完成安装后重新选择实际本体。原件保留；备份与恢复副本共两份完整数据。请选完整安装目录；单独的 EXE 若依赖旁边的库，不能脱离它们运行。</p><p>确认配方计划会采用新共享默认版并绑定所选平台；其它平台的本体未更新时会明确报不匹配。在途 run 保留原锁。撤销导入可恢复旧指针和绑定，两个冻结版本与备份保留。</p>
    <button className="primary-small" disabled={working || !platformId || !id} onClick={()=>plan(async()=>{const value=placement || await api.previewSoftwareBodyPlacement({workspaceRoot:workspace,intake,platformId,softwareId:id});setPlacement(value);return value;})}>1. 预览安置／继续与恢复</button>
    {placement && <><div className="path-line">拟安置：{placement.target.path}<br />程序入口：{placement.target.path+'\\'+placement.target.entry}<br />备份：{placement.target.backup}</div><button className="small-button" disabled={working} onClick={async()=>{setError('');try{const value=await api.verifyPlan({plan:placement});setResult(value);if(!value.ok)setError('本体尚未安置或回读未通过，请先确认执行安置计划。');}catch(error){setError(friendlyError(error));}}}>读取实际安置结果</button></>}
    <div className="wizard-field"><label>软件形式</label><select value={mode} onChange={event=>setMode(event.target.value)}><option value="cli">CLI／脚本：映射具体动作</option><option value="gui">GUI：启动、检查存活、关闭本次会话</option></select></div>
    {mode==='cli'?<><div className="wizard-field"><label>脚本解释器（EXE 可留空；Python 可使用本平台解释器）</label><input value={runtime} onChange={event=>setRuntime(event.target.value)} /><button className="small-button" onClick={async()=>{const path=await api.selectOnboardingFile();if(path)setRuntime(path);else setError('已取消选择。');}}>选择运行程序</button></div><div className="wizard-field"><label>版本查询参数（每行一项）</label><textarea rows={2} value={versionArgs} onChange={event=>setVersionArgs(event.target.value)} /></div>
      {actions.map((action,index)=><fieldset key={index}><legend>功能 {index+1}</legend><div className="wizard-grid"><label>动作名称<input value={action.name} onChange={event=>update(index,{name:event.target.value})} /></label><label>固定参数（每行一项）<textarea value={action.args} onChange={event=>update(index,{args:event.target.value})} /></label><label>影响<select value={action.sideEffects} onChange={event=>update(index,{sideEffects:event.target.value,probeReadOnly:false})}><option value="none">只读</option><option value="local-write">本机写入</option><option value="external">外部操作</option></select></label><label>文件范围<select value={action.filesystem} onChange={event=>update(index,{filesystem:event.target.value})}><option value="none">无</option><option value="read">读取</option><option value="workspace">项目工作区</option></select></label><label>网络范围<select value={action.network} onChange={event=>update(index,{network:event.target.value,probeReadOnly:false})}><option value="none">无</option><option value="loopback">本机回环</option><option value="public">公开网络（每次确认）</option></select></label></div>
        {action.parameters.map((parameter,p)=><div className="wizard-grid" key={p}><label>参数名<input value={parameter.name} onChange={event=>update(index,{parameters:action.parameters.map((row,i)=>i===p?{...row,name:event.target.value}:row)})} /></label><label>命令标记<input value={parameter.flag} onChange={event=>update(index,{parameters:action.parameters.map((row,i)=>i===p?{...row,flag:event.target.value}:row)})} placeholder="--input" /></label><label>类型<select value={parameter.type} onChange={event=>update(index,{parameters:action.parameters.map((row,i)=>i===p?{...row,type:event.target.value}:row)})}><option value="string">文字</option><option value="integer">整数</option><option value="boolean">true / false</option></select></label><label>排列<select value={parameter.style} onChange={event=>update(index,{parameters:action.parameters.map((row,i)=>i===p?{...row,style:event.target.value}:row)})}><option value="repeat">标记 空格 值</option><option value="equals">标记=值</option><option value="positional">只传值</option></select></label><label>只读测试值<input value={parameter.testValue} onChange={event=>update(index,{parameters:action.parameters.map((row,i)=>i===p?{...row,testValue:event.target.value}:row)})} /></label><label><input type="checkbox" checked={parameter.required} onChange={event=>update(index,{parameters:action.parameters.map((row,i)=>i===p?{...row,required:event.target.checked}:row)})} />必填</label><button className="small-button" onClick={()=>update(index,{parameters:action.parameters.filter((_,i)=>i!==p)})}>移除参数</button></div>)}
        <div className="git-actions"><button className="small-button" onClick={()=>update(index,{parameters:[...action.parameters,{name:'',flag:'',type:'string',style:'repeat',required:false,testValue:''}]})}>添加参数</button><button className="small-button" onClick={()=>setActions(rows=>rows.filter((_,i)=>i!==index))}>移除动作</button><label><input type="checkbox" disabled={action.sideEffects!=='none' || action.network!=='none' || action.filesystem==='workspace'} checked={action.probeReadOnly} onChange={event=>update(index,{probeReadOnly:event.target.checked})} />我确认现在执行这条只读功能测试</label></div></fieldset>)}<button className="small-button" onClick={()=>setActions(rows=>[...rows,newAction()])}>添加功能动作</button></>:<div className="wizard-field"><label>启动参数（每行一项，可留空）</label><textarea value={launchArgs} onChange={event=>setLaunchArgs(event.target.value)} /><p>GUI 内部操作仍由你完成。会话启动不等于程序功能已自动化或已验证。</p></div>}
    <div className="git-actions"><button className="primary-small" disabled={working || !placement || !displayName || mode==='cli' && !upstream} onClick={()=>plan(()=>api.previewSoftwareBody({workspaceRoot:workspace,platformId,placementPlan:placement,displayName,upstreamVersion:upstream || 'unknown',releaseVersion:version || null,mode,runtimeExecutable:runtime,versionArgs:versionArgs.split(/\r?\n/).filter(Boolean),actions:serialize(),launchArgs:launchArgs.split(/\r?\n/).filter(Boolean)}))}>{mode==='cli'?'2. 只读询问并预览配方与绑定':'2. 预览 GUI 会话配方与绑定'}</button><button className="small-button" disabled={working || !id} onClick={()=>relay('call')}>预览查询现行版本</button>{['open','status','close'].map(operation=><button className="small-button" disabled={working || !id} key={operation} onClick={()=>relay(operation)}>{({open:'预览启动本次会话',status:'预览检查会话存活',close:'预览关闭本次会话'})[operation]}</button>)}</div>
    {error && <div className="scan-result warning" role="alert">{error}</div>}{result && <div className={'scan-result '+(result.ok?'clean':'warning')}>{result.ok?'安置和真实恢复已通过。':'尚未通过安置回读。'}<div className="path-line">{result.entry || result.target}</div></div>}
  </section>;
}
