import React,{useEffect,useRef,useState} from 'react';
import {friendlyError} from '../../presenter.mjs';
export function ToolBodyForm({api,workspace,platformId,intake=null,resource=null,setPlanPreview,setPlanPayload,setMessage,onClose=null}) {
  const [editor,setEditor]=useState(null),[fields,setFields]=useState({resourceId:'',version:'1.0.0',displayName:'',dependencies:{workflows:{},skills:{},packs:{}}}),[body,setBody]=useState(''),[stages,setStages]=useState([]),[editStages,setEditStages]=useState(false),[error,setError]=useState(''),[working,setWorking]=useState(false),[options,setOptions]=useState(null),[filter,setFilter]=useState('');const serial=useRef(0);
  useEffect(()=>{const current=++serial.current;setEditor(null);setError('');Promise.all([api.readToolBodyEditor({workspaceRoot:workspace,platformId,intake,...resource}),api.listBodyDependencies({workspaceRoot:workspace})]).then(([value,choices])=>{if(current!==serial.current)return;setEditor(value);setFields(value.fields);setBody(value.definition?'':value.content);setOptions(choices);setEditStages(!value.definition);setStages(value.definition?.stages?.map(row=>({...row,body:value.stageBodies?.[row.id]})) || (value.intake && /\.(py|js|mjs|ps1|sh)$/i.test(value.intake.selectedEntry)?[{id:'RUN',action:'script',worker:'expert',script:'original/'+value.intake.selectedEntry,arguments:{argv:[],timeoutSeconds:30}}]:[{id:'INTAKE',action:'prompt',worker:'expert',body:value.content}]));}).catch(error=>{if(current===serial.current)setError(friendlyError(error));});return ()=>{serial.current++;};},[api,workspace,platformId,intake,resource]);
  const update=(key,value)=>setFields(previous=>({...previous,[key]:value}));
  const stage=(index,key,value)=>setStages(previous=>previous.map((row,position)=>position===index?{...row,[key]:value}:row));
  const preview=async()=>{setWorking(true);setError('');try{const plan=await api.previewToolBody({workspaceRoot:workspace,platformId,intake:editor.intake,...fields,content:editStages?body:undefined,stages:editStages?stages:null,manifest:editor.manifest,definition:editor.definition,adopt:true});setPlanPreview(plan);setPlanPayload(null);setMessage('工作流接入计划已生成，尚未执行脚本或正文任务。');}catch(error){setError(friendlyError(error));}finally{setWorking(false);}};
  return <section className="panel"><div className="panel-title"><span>{resource?'编辑工作流并发布更新':'工作流正文与阶段设置'}</span>{onClose && <button className="small-button" onClick={onClose}>关闭编辑</button>}</div>{error && <div className="scan-result warning" role="alert">{error}</div>}
    {!editor?<p>正在读取来源与已有定义…</p>:<>
      <div className="wizard-grid"><div className="wizard-field"><label>资源 ID</label><input value={fields.resourceId} readOnly={fields.updating} onChange={event=>update('resourceId',event.target.value)} placeholder="my-workflow" /></div><div className="wizard-field"><label>显示名称</label><input value={fields.displayName} onChange={event=>update('displayName',event.target.value)} /></div><div className="wizard-field"><label>新版本</label><input value={fields.version} onChange={event=>update('version',event.target.value)} /></div></div>
      {editor.definition && <><label><input type="checkbox" checked={editStages} onChange={event=>setEditStages(event.target.checked)} />修改阶段（未勾选时保留原定义和所有支持文件，只更新身份）</label><details><summary>查看完整原定义</summary><pre>{JSON.stringify(editor.definition,null,2)}</pre></details></>}
      {editStages && <><p>按顺序填写阶段。提示词由客户端处理；脚本只有在用户明确启动业务、并满足平台隔离条件时才执行。</p><div className="wizard-field"><label>任务说明</label><textarea rows={7} value={body} onChange={event=>setBody(event.target.value)} /></div>
        {stages.map((row,index)=><div className="notice" key={index}><div className="wizard-grid"><div className="wizard-field"><label>阶段 ID</label><input value={row.id} onChange={event=>stage(index,'id',event.target.value)} /></div><div className="wizard-field"><label>动作</label><select value={row.action} onChange={event=>stage(index,'action',event.target.value)}><option value="prompt">提示词</option><option value="script">原始脚本</option>{!['prompt','script'].includes(row.action) && <option value={row.action}>保留原动作：{row.action}</option>}</select></div>
          {row.action==='script' && <div className="wizard-field"><label>脚本入口</label><select value={row.script || ''} onChange={event=>stage(index,'script',event.target.value)}><option value="">请选择脚本</option>{editor.intake?.files.filter(file=>file.included && /\.(py|js|mjs|ps1|sh)$/i.test(file.path)).map(file=><option key={file.path} value={'original/'+file.path}>{file.path}</option>)}</select><small>EXE／DLL 等程序本体请按软件接入。</small></div>}
        </div>{row.action==='prompt' && <div className="wizard-field"><label>本阶段说明（留空使用上方任务说明）</label><textarea rows={4} value={row.body || ''} onChange={event=>stage(index,'body',event.target.value)} /></div>}{row.action==='script' && <><div className="wizard-field"><label>脚本参数（每行一个原样参数）</label><textarea rows={3} value={(row.arguments?.argv || []).join('\n')} onChange={event=>stage(index,'arguments',{...row.arguments,argv:event.target.value.split(/\r?\n/).filter(line=>line.length)})} /></div><div className="wizard-field"><label>超时秒数</label><input type="number" min="1" max="3600" value={row.arguments?.timeoutSeconds || 30} onChange={event=>stage(index,'arguments',{...row.arguments,timeoutSeconds:Number(event.target.value)})} /></div></>}
          <button className="small-button" disabled={stages.length===1} onClick={()=>setStages(previous=>previous.filter((_,position)=>position!==index))}>移除此阶段</button></div>)}<button className="small-button" onClick={()=>setStages(previous=>[...previous,{id:'STEP_'+(previous.length+1),action:'prompt',worker:'expert'}])}>添加阶段</button>
      </>}
      <details><summary>精确技能依赖</summary><input value={filter} onChange={event=>setFilter(event.target.value)} placeholder="筛选技能（显示前 50 条）" />{options.skills.filter(row=>!filter || row.id.includes(filter)).slice(0,50).map(row=><label className="dependency-choice" key={row.id}><input type="checkbox" checked={Boolean(fields.dependencies.skills?.[row.id])} onChange={event=>{const pins={...fields.dependencies.skills};if(event.target.checked)pins[row.id]=row.version;else delete pins[row.id];update('dependencies',{...fields.dependencies,skills:pins});}} />{row.id}@{row.version}</label>)}<p>已选：{Object.entries(fields.dependencies.skills || {}).map(([id,pin])=>id+'@'+pin).join('、') || '无'}</p></details>
      <div className="git-actions"><button className="primary-small" disabled={working || !platformId || !fields.resourceId || editStages && !stages.length} onClick={preview}>{working?'检查定义与依赖…':'预览接入／更新'}</button></div>
    </>}
  </section>;
}
