// Onboarding domain (3.5.0 P7/P8): scaffold a brand-new platform directory,
// generate §9-keyed config skeletons, draft the governance-document additions,
// and produce the real-submission instruction card. Creating a first-level
// directory requires the user's explicit confirmation flag (the BP-1
// authorization act) and never runs without a plan.
import { existsSync, mkdirSync, readFileSync, unlinkSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { isFormalPlatform, PLATFORM_IDS } from './core/platforms.mjs';
import { sha256 } from './core/hash.mjs';
import { targetPath } from './core/paths.mjs';
import { atomicWrite, makeId, output, requirePlan, writeAudit } from './transactions/kernel.mjs';
import { inspectPlatformConnection, runPlatformCheck } from './platform-check.mjs';

const PLATFORM_ID = /^[a-z][a-z0-9-]{1,30}$/;

function bridgeJsonFor(root, platformId, displayName) {
  return `${JSON.stringify({
    schema: 'ai-platform-bridge/v1.1',
    platform: platformId,
    displayName,
    shared: {
      agentRegistry: `${root.replaceAll('\\', '/')}/agent/registry.json`,
      toolRegistry: `${root.replaceAll('\\', '/')}/tool/registry.json`,
      architecturePrompt: `${root.replaceAll('\\', '/')}/AI_ARCHITECTURE_SYSTEM_PROMPT.md`,
      readOnly: true
    },
    runtimeRoot: join(root, platformId, 'runtime'),
    runner: `${root.replaceAll('\\', '/')}/tool/wf-runner`,
    modes: ['workflow', 'agent-workflow'],
    notes: 'scaffold generated by architecture-manager; every §9 key must be completed and self-certified before this platform is called 接入'
  }, null, 2)}\n`;
}

function platformConfigFor(root, platformId) {
  return `${JSON.stringify({
    platform: platformId,
    platformRoot: join(root, platformId),
    toolRoot: join(root, 'tool'),
    agentRoot: join(root, 'agent'),
    runsRoot: join(root, platformId, 'runtime', 'runs'),
    runner: join(root, 'tool', 'wf-runner', 'versions', '<PIN>'),
    contracts: join(root, 'tool', 'runtime-contracts', 'versions', '<PIN>'),
    bridge: join(root, platformId, 'bridge.json'),
    capabilities: join(root, platformId, 'bridge', 'capabilities.json'),
    scannerRelease: 'repo-lint/<PIN — must pair with the repo-lint run version (D-52)>',
    pendingKeys: ['runner pin', 'contracts pin', 'scannerRelease', 'executionBackend?', 'peer keys?', 'software keys?'],
    notes: 'skeleton only; replace every <PIN> and declare only what this platform actually verified'
  }, null, 2)}\n`;
}

function capabilitiesFor(platformId) {
  return `${JSON.stringify({
    schema: 'ai-platform-capabilities/v2',
    platform: platformId,
    declared: {},
    declaredAbsent: [
      { facet: 'scriptEnvironment', reason: 'not yet built or verified', closePath: 'declare executionBackend + sealed environment, then self-certify' },
      { facet: 'peerDispatch', reason: 'not yet verified', closePath: 'declare peerDispatcherModule + peerContentRoot together, then self-certify' }
    ],
    notes: 'honest floor: everything starts absent until this platform proves it (BP-2)'
  }, null, 2)}\n`;
}

function platformChapterFor(platformId, displayName) {
  return `# ${displayName || platformId}（平台章）

> 本平台章由 ${platformId} 平台自己的会话维护；其他会话不要代写接入结论（BP-2）。
> 接入判据：§9 八项接口 + 矩阵 FAIL 0 + 能力并集 0 declaredAbsent，全部由本平台自己出证。

## 接入状态

- [ ] 目录与 bridge 脚手架（architecture-manager 生成，待补 <PIN>）
- [ ] bridge/config/capabilities 逐键完成
- [ ] 矩阵 FAIL 0（本平台自证）
- [ ] conform 0 declaredAbsent
- [ ] 真实提交一格闭环
`;
}

function maintenanceTemplateFor(platformId) {
  return `# ${platformId} runtime 维护区

本目录只放登记形维护产物（agent/workflow = null，不冒充业务 run）。
`;
}

export function buildPlatformScaffoldPlan({ workspaceRoot, platformId, displayName = '', confirmed = false, now = new Date().toISOString() }) {
  if (confirmed !== true) throw new Error('PLATFORM_SCAFFOLD_CONFIRMATION_REQUIRED');
  if (!PLATFORM_ID.test(String(platformId || ''))) throw new Error('INVALID_PLATFORM_ID');
  if (isFormalPlatform(platformId) || PLATFORM_IDS.includes(platformId)) throw new Error('PLATFORM_ID_RESERVED');
  const root = resolve(workspaceRoot);
  const platformRoot = targetPath(root, platformId);
  if (existsSync(platformRoot)) throw new Error('PLATFORM_DIRECTORY_EXISTS');
  const files = [
    { path: `${platformId}/bridge.json`, content: bridgeJsonFor(root, platformId, displayName) },
    { path: `${platformId}/bridge/platform.md`, content: platformChapterFor(platformId, displayName) },
    { path: `${platformId}/bridge/${platformId}-config.json`, content: platformConfigFor(root, platformId) },
    { path: `${platformId}/bridge/capabilities.json`, content: capabilitiesFor(platformId) },
    { path: `${platformId}/runtime/.gitkeep`, content: '' },
    { path: `${platformId}/runtime/maintenance/README.md`, content: maintenanceTemplateFor(platformId) }
  ];
  return {
    schema: 'architecture-manager-plan/v1',
    planId: `platform-scaffold-${platformId}-${now.replace(/[^0-9]/g, '').slice(0, 17)}`,
    kind: 'platform-scaffold',
    workspaceRoot: root,
    generatedAt: now,
    applyMode: 'confirmation-required',
    writePerformed: false,
    target: { platformId, displayName, directory: platformId, userAuthorized: true },
    steps: [{ operation: 'create-platform-directory', files: files.map((file) => file.path) }],
    verification: ['re-check the platform directory does not exist before apply', 'write every scaffold file atomically', 'remove created files on failure'],
    payload: { files }
  };
}

export function applyPlatformScaffold(plan, context) {
  requirePlan(plan);
  const root = resolve(plan.workspaceRoot);
  const platformRoot = join(root, plan.target.platformId);
  if (existsSync(platformRoot)) throw new Error('PLATFORM_DIRECTORY_EXISTS');
  const id = makeId(plan, context.now);
  const created = [];
  for (const file of plan.payload.files) {
    if (existsSync(join(root, file.path))) throw new Error('PLATFORM_SCAFFOLD_TARGET_EXISTS');
  }
  try {
    for (const file of plan.payload.files) {
      const target = join(root, file.path);
      mkdirSync(join(target, '..'), { recursive: true });
      atomicWrite(target, file.content, id);
      created.push(target);
    }
    const event = writeAudit({ ...context, transactionId: id, plan, action: 'platform-scaffold', status: 'applied', target: plan.target.directory, newSha256: sha256(plan.payload.files.map((file) => file.path).join('\n')), writePerformed: true });
    return output(event);
  } catch (error) {
    for (const path of created) {
      try { unlinkSync(path); } catch { /* leave diagnostic */ }
    }
    throw error;
  }
}

export function governanceOnboardingDraft(workspaceRoot, platformId) {
  if (!PLATFORM_ID.test(String(platformId || ''))) throw new Error('INVALID_PLATFORM_ID');
  const drafts = [
    { path: 'AGENTS.md', section: '一级目录清单', draft: `在正式一级目录清单中加入 \`${platformId}\`（用户已确认授权；登记见更新日志）。` },
    { path: 'AI_ARCHITECTURE_SYSTEM_PROMPT.md', section: '运行平台列表', draft: `运行平台目录新增 \`${platformId}\`（目录与 bridge 脚手架已生成，接入判据未达成前不得写成已接入）。` },
    { path: 'HANDOFF.md', section: '平台章表', draft: `| ${platformId} | ${platformId}/bridge/platform.md |（接入判据达成后补充读数）` },
    { path: 'versions/平台接入清单.md', section: '新 §', draft: `### §8.x 〔${new Date().toISOString().slice(0, 10)} ${platformId} 接入轮〕\n- 脚手架来源：architecture-manager 接入向导；矩阵/conform 证据待本平台自证。` },
    { path: 'versions/更新日志.md', section: '新条目', draft: `- ${new Date().toISOString().slice(0, 10)}：\`${platformId}\` 平台目录脚手架生成（architecture-manager），接入判据未达成。` }
  ];
  return { platformId, drafts };
}

export function buildOnboardingCard(workspaceRoot, platformId) {
  const root = resolve(workspaceRoot);
  const exists = existsSync(join(root, platformId, 'bridge.json'));
  return {
    platformId,
    scaffoldPresent: exists,
    card: [
      `【真实提交一格指令卡 · ${platformId}】`,
      '1. 打开该平台自己的 AI 会话（这是唯一需要平台 AI 的环节）。',
      '2. 在会话里执行：/wf repo-lint 对当前工作区做一次只读扫描并输出结论。',
      '3. 回到管理台读回核验：runtime/runs/<run-id>/run-lock.json 应存在，selection.workflow 应为 workflow:repo-lint。',
      '4. 该格通过后，矩阵 FAIL 0 与 conform 0 declaredAbsent 仍需按判据完成；不得以本格替代。'
    ].join('\n'),
    readback: ['run-lock.json 存在', 'schemaVersion 为 ai-run-lock/v1.x', 'selection.workflow 命中', '终态非 prepared']
  };
}

// One-click pipeline (3.5.0 P8): precheck -> quick conform -> optional full
// matrix, stopping at the first failed stage. Runs the platform's own checks
// (runPlatformCheck writes evidence under the platform's runtime/manager-check).
export function runOnboardingPipeline({ workspaceRoot, platformId, includeMatrix = false }) {
  const steps = [];
  let precheck;
  try {
    precheck = inspectPlatformConnection({ workspaceRoot, platformId });
  } catch (error) {
    precheck = { ok: false, error: String(error?.message ?? error) };
  }
  steps.push({ step: 'precheck', result: precheck });
  if (precheck.ok === false || precheck.valid === false) return { platformId, steps, stoppedAt: 'precheck' };
  const quick = runPlatformCheck({ workspaceRoot, platformId, mode: 'quick' });
  steps.push({ step: 'conform-quick', result: quick });
  if (quick.issues?.length > 0) return { platformId, steps, stoppedAt: 'conform-quick' };
  if (includeMatrix) {
    const full = runPlatformCheck({ workspaceRoot, platformId, mode: 'full' });
    steps.push({ step: 'matrix-full', result: full });
    if (full.issues?.length > 0) return { platformId, steps, stoppedAt: 'matrix-full' };
  }
  return { platformId, steps, stoppedAt: null };
}
