// Onboarding domain (3.5.0 P7/P8): scaffold a brand-new platform directory,
// generate §9-keyed config skeletons, draft the governance-document additions,
// and produce the real-submission instruction card. Creating a first-level
// directory requires the user's explicit confirmation flag (the BP-1
// authorization act) and never runs without a plan.
import { existsSync, mkdirSync, readFileSync, unlinkSync, rmdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { isFormalPlatform, PLATFORM_IDS } from './core/platforms.mjs';
import { sha256 } from './core/hash.mjs';
import { targetPath } from './core/paths.mjs';
import { atomicWrite, makeId, output, requirePlan, saveCheckpoint, writeAudit } from './transactions/kernel.mjs';
import { inspectPlatformConnection, runPlatformCheck } from './platform-check.mjs';

const PLATFORM_ID = /^[a-z][a-z0-9-]{1,30}$/;

function bridgeJsonFor(root, platformId, displayName) {
  return `${JSON.stringify({
    schema: 'ai-platform-bridge/v1.1',
    platform: platformId,
    displayName,
    shared: {
      agentRegistry: `${root.replaceAll('\\', '/')}/agent/registry.json`,
      toolRegistry: `${root.replaceAll('\\', '/')}/tool/registry.json`,
      architecturePrompt: `${root.replaceAll('\\', '/')}/AI_ARCHITECTURE_SYSTEM_PROMPT.md`,
      readOnly: true
    },
    runtimeRoot: join(root, platformId, 'runtime'),
    runner: `${root.replaceAll('\\', '/')}/tool/wf-runner`,
    modes: ['workflow', 'agent-workflow'],
    notes: 'scaffold generated by architecture-manager; every §9 key must be completed and self-certified before this platform is called 接入'
  }, null, 2)}\n`;
}

function platformConfigFor(root, platformId) {
  return `${JSON.stringify({
    platform: platformId,
    platformRoot: join(root, platformId),
    toolRoot: join(root, 'tool'),
    agentRoot: join(root, 'agent'),
    runsRoot: join(root, platformId, 'runtime', 'runs'),
    runner: join(root, 'tool', 'wf-runner', 'versions', '<PIN>'),
    contracts: join(root, 'tool', 'runtime-contracts', 'versions', '<PIN>'),
    bridge: join(root, platformId, 'bridge.json'),
    capabilities: join(root, platformId, 'bridge', 'capabilities.json'),
    scannerRelease: 'repo-lint/<PIN — must pair with the repo-lint run version (D-52)>',
    pendingKeys: ['runner pin', 'contracts pin', 'scannerRelease', 'executionBackend?', 'peer keys?', 'software keys?'],
    notes: 'skeleton only; replace every <PIN> and declare only what this platform actually verified'
  }, null, 2)}\n`;
}

function capabilitiesFor(platformId) {
  return `${JSON.stringify({
    schema: 'ai-platform-capabilities/v2',
    platform: platformId,
    declared: {},
    declaredAbsent: [
      { facet: 'scriptEnvironment', reason: 'not yet built or verified', closePath: 'declare executionBackend + sealed environment, then self-certify' },
      { facet: 'peerDispatch', reason: 'not yet verified', closePath: 'declare peerDispatcherModule + peerContentRoot together, then self-certify' }
    ],
    notes: 'honest floor: everything starts absent until this platform proves it (BP-2)'
  }, null, 2)}\n`;
}

function platformChapterFor(platformId, displayName) {
  return `# ${displayName || platformId}（平台章）

> 本平台章由 ${platformId} 平台自己的会话维护；其他会话不要代写接入结论（BP-2）。
> 接入判据：§9 八项接口 + 矩阵 FAIL 0 + 能力并集 0 declaredAbsent，全部由本平台自己出证。

## 接入状态

- [ ] 目录与 bridge 脚手架（architecture-manager 生成，待补 <PIN>）
- [ ] bridge/config/capabilities 逐键完成
- [ ] 矩阵 FAIL 0（本平台自证）
- [ ] conform 0 declaredAbsent
- [ ] 真实提交一格闭环
`;
}

function maintenanceTemplateFor(platformId) {
  return `# ${platformId} runtime 维护区

本目录只放登记形维护产物（agent/workflow = null，不冒充业务 run）。
`;
}

export function buildPlatformScaffoldPlan({ workspaceRoot, platformId, displayName = '', confirmed = false, now = new Date().toISOString() }) {
  if (confirmed !== true) throw new Error('PLATFORM_SCAFFOLD_CONFIRMATION_REQUIRED');
  if (!PLATFORM_ID.test(String(platformId || ''))) throw new Error('INVALID_PLATFORM_ID');
  if (isFormalPlatform(platformId) || PLATFORM_IDS.includes(platformId)) throw new Error('PLATFORM_ID_RESERVED');
  const root = resolve(workspaceRoot);
  const platformRoot = targetPath(root, platformId);
  if (existsSync(platformRoot)) throw new Error('PLATFORM_DIRECTORY_EXISTS');
  const files = [
    { path: `${platformId}/bridge.json`, content: bridgeJsonFor(root, platformId, displayName) },
    { path: `${platformId}/bridge/platform.md`, content: platformChapterFor(platformId, displayName) },
    { path: `${platformId}/bridge/${platformId}-config.json`, content: platformConfigFor(root, platformId) },
    { path: `${platformId}/bridge/capabilities.json`, content: capabilitiesFor(platformId) },
    { path: `${platformId}/runtime/.gitkeep`, content: '' },
    { path: `${platformId}/runtime/maintenance/README.md`, content: maintenanceTemplateFor(platformId) }
  ];
  return {
    schema: 'architecture-manager-plan/v1',
    planId: `platform-scaffold-${platformId}-${now.replace(/[^0-9]/g, '').slice(0, 17)}`,
    kind: 'platform-scaffold',
    workspaceRoot: root,
    generatedAt: now,
    applyMode: 'confirmation-required',
    writePerformed: false,
    target: { platformId, displayName, directory: platformId, userAuthorized: true },
    steps: [{ operation: 'create-platform-directory', files: files.map((file) => file.path) }],
    verification: ['re-check the platform directory does not exist before apply', 'write every scaffold file atomically', 'remove created files on failure'],
    payload: { files }
  };
}

export function applyPlatformScaffold(plan, context) {
  requirePlan(plan);
  const root = resolve(plan.workspaceRoot);
  if (plan.target?.userAuthorized !== true || plan.target.directory !== plan.target.platformId) throw new Error('INVALID_PLATFORM_SCAFFOLD_PLAN');
  const expected = buildPlatformScaffoldPlan({ workspaceRoot: root, platformId: plan.target.platformId, displayName: plan.target.displayName, confirmed: true, now: plan.generatedAt });
  if (JSON.stringify(plan.payload?.files) !== JSON.stringify(expected.payload.files)) throw new Error('PLAN_PAYLOAD_MISMATCH');
  const platformRoot = targetPath(root, plan.target.platformId);
  if (existsSync(platformRoot)) throw new Error('PLATFORM_DIRECTORY_EXISTS');
  const id = makeId(plan, context.now);
  const created = [];
  const directories = new Set();
  for (const file of plan.payload.files) {
    if (existsSync(targetPath(root, file.path))) throw new Error('PLATFORM_SCAFFOLD_TARGET_EXISTS');
  }
  const checkpoint = saveCheckpoint(context.auditRoot, id, JSON.stringify({ kind: plan.kind, platformId: plan.target.platformId, files: plan.payload.files.map((file) => ({ path: file.path, before: null, newSha256: sha256(file.content) })) }));
  try {
    mkdirSync(platformRoot);
    directories.add(platformRoot);
    for (const file of plan.payload.files) {
      const target = targetPath(root, file.path);
      if (existsSync(target)) throw new Error('PLATFORM_SCAFFOLD_TARGET_EXISTS');
      let directory = dirname(target);
      while (directory.startsWith(platformRoot) && !existsSync(directory)) { directories.add(directory); directory = dirname(directory); }
      mkdirSync(dirname(target), { recursive: true });
      atomicWrite(target, file.content, id);
      created.push(target);
    }
    const event = writeAudit({ ...context, transactionId: id, plan, action: 'platform-scaffold', status: 'applied', target: plan.target.directory, newSha256: sha256(JSON.stringify(plan.payload.files)), checkpointPath: checkpoint.path, checkpointSha256: checkpoint.sha256, writePerformed: true });
    return output(event, checkpoint.path);
  } catch (error) {
    for (const path of created) {
      try { unlinkSync(path); } catch { /* leave diagnostic */ }
    }
    for (const directory of [...directories].sort((a, b) => b.length - a.length)) { try { rmdirSync(directory); } catch { /* Never remove somebody else's new files. */ } }
    writeAudit({ ...context, transactionId: id, plan, action: 'platform-scaffold', status: 'failed-restored', target: plan.target.directory, checkpointPath: checkpoint.path, checkpointSha256: checkpoint.sha256, error: String(error.message) });
    throw error;
  }
}

export function verifyPlatformScaffold(plan) {
  requirePlan(plan);
  const expected = plan.payload?.files;
  if (!Array.isArray(expected) || expected.length !== 6) throw new Error('INVALID_PLATFORM_SCAFFOLD_PLAN');
  const files = expected.map((file) => {
    const path = targetPath(plan.workspaceRoot, file.path);
    const actual = existsSync(path) ? sha256(readFileSync(path)) : null;
    return { path: file.path, ok: actual === sha256(file.content), actualSha256: actual };
  });
  return { schema: 'architecture-manager-verification/v1', ok: files.every((file) => file.ok), files, writePerformed: false };
}

export function governanceOnboardingDraft(workspaceRoot, platformId) {
  if (!PLATFORM_ID.test(String(platformId || ''))) throw new Error('INVALID_PLATFORM_ID');
  const drafts = [
    { path: 'AGENTS.md', section: '一级目录清单', draft: `在正式一级目录清单中加入 \`${platformId}\`（用户已确认授权；登记见更新日志）。` },
    { path: 'AI_ARCHITECTURE_SYSTEM_PROMPT.md', section: '运行平台列表', draft: `运行平台目录新增 \`${platformId}\`（目录与 bridge 脚手架已生成，接入判据未达成前不得写成已接入）。` },
    { path: 'HANDOFF.md', section: '平台章表', draft: `| ${platformId} | ${platformId}/bridge/platform.md |（接入判据达成后补充读数）` },
    { path: 'versions/平台接入清单.md', section: '新 §', draft: `### §8.x 〔${new Date().toISOString().slice(0, 10)} ${platformId} 接入轮〕\n- 脚手架来源：architecture-manager 接入向导；矩阵/conform 证据待本平台自证。` },
    { path: 'versions/更新日志.md', section: '新条目', draft: `- ${new Date().toISOString().slice(0, 10)}：\`${platformId}\` 平台目录脚手架生成（architecture-manager），接入判据未达成。` }
  ];
  return { platformId, drafts };
}

export function buildOnboardingCard(workspaceRoot, platformId) {
  const root = resolve(workspaceRoot);
  const exists = existsSync(join(root, platformId, 'bridge.json'));
  return {
    platformId,
    scaffoldPresent: exists,
    card: [
      `【无需维护型 AI 的接入指引 · ${platformId}】`,
      '1. 在平台接入向导选择本平台，保存配置、独立环境与客户端入口。',
      '2. 运行客户端工具回环：真实 CLI/MCP 入口返回本次 challenge 与配置、钉版摘要。',
      '3. 首次接入完成本平台 conform 和完整矩阵；后续修复仅重跑受影响格。',
      '4. 应用治理登记并提交配置，回读接入完成记录；不得以工具握手替代全部判据。业务 AI 输出质量另行验证。'
    ].join('\n'),
    readback: ['配置与环境摘要匹配', '本次客户端 challenge 回执匹配', '首次矩阵 FAIL/NEEDS-INPUT 为 0', 'conform floorReached 为 true', '治理和 Git 回读通过']
  };
}

// Compatibility facade: one certification operation chooses its own scope.
// Never run a redundant quick check before the initial/full request.
export async function runOnboardingPipeline({ workspaceRoot, platformId, includeMatrix = false }, { inspect = inspectPlatformConnection, check = runPlatformCheck } = {}) {
  const steps = [];
  let precheck;
  try {
    precheck = inspect({ workspaceRoot, platformId });
  } catch (error) {
    precheck = { ok: false, error: String(error?.message ?? error) };
  }
  steps.push({ step: 'precheck', result: precheck });
  if (!['configured', 'callable', 'complete', 'check-failed', 'check-cancelled'].includes(precheck.stage)) return { platformId, steps, stoppedAt: 'precheck' };
  const checked = await check({ workspaceRoot, platformId, mode: includeMatrix?'full':'quick' });
  steps.push({ step: 'certification', result: checked });
  if (checked.issues?.length > 0) return { platformId, steps, stoppedAt: 'certification' };
  return { platformId, steps, stoppedAt: null };
}
