import React from 'react';

export function CatalogPanel({ api, workspace, inventory, catalogFilter, setCatalogFilter, agents, skills, skillFilter, setSkillFilter, catalogDetail, setCatalogDetail, skillDetail, setSkillDetail, openCatalog, previewRegistryAction, friendlyError, setMessage }) {
  const [page, setPage] = useState(0);
  const PAGE_SIZE = 50;
  const openSkillContent = async (item) => {
    try {
      const detail = await api.readCatalogEntry({ workspaceRoot: workspace, kind: 'skill', id: item.id });
      const visibleSkills = detail.catalog?.skills?.filter((skill) => !skillFilter || skill.id.toLowerCase().includes(skillFilter.toLowerCase()));
      setPage(0); setSkillDetail({ ...detail, visibleSkills }); setMessage(`已打开 ${item.id} 技能目录，当前显示前 50 条。`);
    } catch (error) { setMessage('读取技能正文失败：' + friendlyError(error)); }
  };
  const readSkill = async (skill) => {
    try { setSkillDetail({ ...skillDetail, selectedSkill: await api.readSkillContent({ workspaceRoot: workspace, catalogId: skillDetail.id, id: skill.id, version: skill.version }) }); setMessage(`已读取 ${skill.id}@${skill.version} 正文。`); }
    catch (error) { setMessage('技能正文读取失败：' + friendlyError(error)); }
  };
  return <section className="panel catalog-panel">
    <div className="panel-title"><span>Agent 与 Skill 管理</span><div className="panel-tools"><input className="filter-input" value={catalogFilter} onChange={(event) => setCatalogFilter(event.target.value)} placeholder="筛选 id" />{inventory && <><button className="small-button" onClick={() => previewRegistryAction('agent', 'add')}>从文件添加 agent</button><button className="small-button" onClick={() => previewRegistryAction('skill', 'add')}>从文件添加 skill 目录</button></>}</div></div>
    <div className="catalog-columns">
      <div><div className="subheading">Agent（{agents.length}）</div>{agents.map((item) => <div className="catalog-row" key={'agent-' + item.id}><div><button className="link-button" onClick={() => openCatalog('agent', item.id)}>{item.id}</button><span className={item.enabled === false ? 'pill' : 'pill good'}>{item.enabled === false ? '停用' : '启用'}</span><div className="resource-repo">当前默认 {item.currentVersion || '未读到'} · registry 登记 {item.registryVersion || '未登记'} · {item.deprecated ? '已弃用' : '现行'}</div></div><div className="resource-actions"><button className="small-button" onClick={() => openCatalog('agent', item.id)}>查看全部</button><button className="small-button" onClick={() => previewRegistryAction('agent', item.enabled === false ? 'enable' : 'disable', item)}>{item.enabled === false ? '启用计划' : '停用计划'}</button><button className="small-button danger-button" onClick={() => previewRegistryAction('agent', 'remove', item)}>移除计划</button></div></div>)}</div>
      <div><div className="subheading">Skill 目录（{skills.length}）</div>{skills.map((item) => <div className="catalog-row" key={'skill-' + item.id}><div><button className="link-button" onClick={() => openCatalog('skill', item.id)}>{item.id}</button><span className={item.enabled === false ? 'pill' : 'pill good'}>{item.enabled === false ? '停用' : '启用'}</span><div className="resource-repo">{item.path}</div></div><div className="resource-actions"><button className="small-button" onClick={() => openCatalog('skill', item.id)}>查看目录</button><button className="small-button" onClick={() => openSkillContent(item)}>查看技能内容</button><button className="small-button" onClick={() => previewRegistryAction('skill', item.enabled === false ? 'enable' : 'disable', item)}>{item.enabled === false ? '启用计划' : '停用计划'}</button><button className="small-button danger-button" onClick={() => previewRegistryAction('skill', 'remove', item)}>移除计划</button></div></div>)}</div>
    </div>
    {catalogDetail && <div className="catalog-detail"><div className="editor-heading"><strong>{catalogDetail.kind} / {catalogDetail.id}</strong><button className="small-button" onClick={() => setCatalogDetail(null)}>关闭详情</button></div><div className="path-line">{catalogDetail.promptPath || catalogDetail.catalogPath || catalogDetail.registryPath}</div><pre>{catalogDetail.kind === 'agent' ? JSON.stringify(catalogDetail.manifest, null, 2) + '\n\n' + (catalogDetail.prompt || '') : catalogDetail.catalogText || JSON.stringify(catalogDetail.catalog, null, 2)}</pre></div>}
    {skillDetail && <div className="catalog-detail"><div className="editor-heading"><strong>{skillDetail.id} 的技能条目（{skillDetail.visibleSkills?.length || 0}/{skillDetail.skillCount}）</strong><div className="panel-tools"><input className="filter-input" value={skillFilter} onChange={(event) => { setSkillFilter(event.target.value); setPage(0); }} placeholder="筛选技能 id" /><button className="small-button" onClick={() => setSkillDetail(null)}>关闭详情</button></div></div><div className="panel-tools"><button className="small-button" disabled={page === 0} onClick={() => setPage(page - 1)}>上一页</button><span className="muted">第 {page + 1} / {Math.max(1, Math.ceil((skillDetail.visibleSkills?.length || 0) / PAGE_SIZE))} 页，每页 50 条</span><button className="small-button" disabled={(page + 1) * PAGE_SIZE >= (skillDetail.visibleSkills?.length || 0)} onClick={() => setPage(page + 1)}>下一页</button></div><div className="skill-detail-list">{(skillDetail.visibleSkills || []).slice(page * PAGE_SIZE, (page + 1) * PAGE_SIZE).map((skill) => <div className="catalog-row" key={skill.id + '-' + skill.version}><span><strong>{skill.id}</strong><span className="resource-repo">v{skill.version} · {skill.sourcePath || ''}</span></span><button className="small-button" onClick={() => readSkill(skill)}>读取正文</button></div>)}</div>{skillDetail.selectedSkill && <pre>{skillDetail.selectedSkill.content}</pre>}</div>}
    {!inventory && <div className="empty">选择工作区后读取 agent registry 和 skill 目录。正文只读查看，启用/停用/移除先生成计划。</div>}
  </section>;
}
