import React from 'react';

export function ResourcePanel({ inventory, resources, resourceFilter, setResourceFilter, targetVersions, setTargetVersions, previewResource }) {
  const visible = resources.filter((resource) => !resourceFilter || (resource.repository + '/' + resource.resourceId).toLowerCase().includes(resourceFilter.toLowerCase()));
  return <section className="panel"><div className="panel-title"><span>三仓资源</span><div className="panel-tools"><input className="filter-input" value={resourceFilter} onChange={(event) => setResourceFilter(event.target.value)} placeholder="筛选资源" /><span className="muted">切换默认版须预览并确认；进行中的任务不变</span></div></div><div className="rows resource-rows">
    {visible.map((resource) => { const key = resource.repository + '/' + resource.resourceId; const selected = targetVersions[key] ?? (resource.latestStableVersion !== resource.version ? resource.latestStableVersion : ''); return <div className="row resource-row" key={key}><div><span className="row-name">{resource.resourceId}</span><span className="resource-repo">{resource.repository}</span><div className="path-line">当前默认：{resource.version || '无'} · 最新稳定版：{resource.latestStableVersion || '无'}</div></div><div className="resource-actions"><span className={resource.valid ? 'pill good' : 'pill warn'}>{resource.version === resource.latestStableVersion ? '已是最新' : '可切换'}</span><select className="version-select" value={selected || ''} onChange={(event) => setTargetVersions((state) => ({ ...state, [key]: event.target.value }))}><option value="">选择已发布版本</option>{resource.availableVersions?.map((version) => <option key={version} value={version}>{version}</option>)}</select><button className="small-button" disabled={!selected || selected === resource.version} onClick={() => previewResource(resource, selected)}>预览切换默认版</button></div></div>; })}
    {!inventory && <div className="empty">选择工作区后显示资源。</div>}{inventory && resources.length === 0 && <div className="empty">没有发现 current.json 指针。</div>}
  </div></section>;
}
