import React,{useState} from 'react';
import {ToolBodyForm} from '../features/intake/ToolBodyForm.jsx';
import {friendlyError} from '../presenter.mjs';

export function ResourcePanel({api,workspace, inventory, resources, resourceFilter, setResourceFilter, targetVersions, setTargetVersions, previewResource,setPlanPreview,setPlanPayload,setMessage }) {
  const [editing,setEditing]=useState(null),[platformId,setPlatformId]=useState(inventory?.platforms?.[0]?.id || ''),[result,setResult]=useState(null),[working,setWorking]=useState(false);
  const check=async resource=>{setWorking(true);setResult(null);try{if(!await api.confirm('仅运行这个工作流的准备、领取、停止链路，不执行阶段业务。'))return;setResult(await api.checkSharedBody({workspaceRoot:workspace,platformId,type:'tool',resourceId:resource.resourceId,version:resource.version}));}catch(error){setResult({ok:false,error:friendlyError(error)});}finally{setWorking(false);}};
  const visible = resources.filter((resource) => !resourceFilter || (resource.repository + '/' + resource.resourceId).toLowerCase().includes(resourceFilter.toLowerCase()));
  return <section className="panel"><div className="panel-title"><span>三仓资源</span><div className="panel-tools"><input className="filter-input" value={resourceFilter} onChange={(event) => setResourceFilter(event.target.value)} placeholder="筛选资源" /><span className="muted">切换默认版须预览并确认；进行中的任务不变</span></div></div><div className="wizard-field"><label>工作流更新／检查所属平台</label><select value={platformId} onChange={event=>{setPlatformId(event.target.value);setResult(null);}}><option value="">请选择</option>{inventory?.platforms?.map(row=><option key={row.id} value={row.id}>{row.id}</option>)}</select></div>{result && <div className={'scan-result '+(result.ok?'clean':'warning')}>{result.ok?'准备、领取、停止通过；业务任务未执行。':result.error || result.issues?.join('；')}{result.evidencePath && <div className="path-line">{result.evidencePath}</div>}</div>}{editing && <ToolBodyForm api={api} workspace={workspace} platformId={platformId} resource={editing} setPlanPreview={setPlanPreview} setPlanPayload={setPlanPayload} setMessage={setMessage} onClose={()=>setEditing(null)} />}<div className="rows resource-rows">
    {visible.map(resource=>{
      const key=resource.repository+'/'+resource.resourceId,selected=targetVersions[key] ?? (resource.latestStableVersion!==resource.version?resource.latestStableVersion:'');
      return <div className="row resource-row" key={key}><div><span className="row-name">{resource.resourceId}</span><span className="resource-repo">{resource.repository}</span><div className="path-line">当前默认：{resource.version || '无'} · 最新稳定版：{resource.latestStableVersion || '无'}</div></div><div className="resource-actions"><span className={resource.valid?'pill good':'pill warn'}>{resource.version===resource.latestStableVersion?'已是最新':'可切换'}</span><select className="version-select" value={selected || ''} onChange={event=>setTargetVersions(state=>({...state,[key]:event.target.value}))}><option value="">选择已发布版本</option>{resource.availableVersions?.map(version=><option key={version} value={version}>{version}</option>)}</select><button className="small-button" disabled={!selected || selected===resource.version} onClick={()=>previewResource(resource,selected)}>预览切换默认版</button>{resource.repository==='tool' && <><button className="small-button" onClick={()=>setEditing({resourceId:resource.resourceId})}>查看／编辑工作流</button><button className="small-button" disabled={working || !platformId} onClick={()=>check(resource)}>最小调用检查</button></>}</div></div>;
    })}
    {!inventory && <div className="empty">选择工作区后显示资源。</div>}{inventory && resources.length === 0 && <div className="empty">没有发现 current.json 指针。</div>}
  </div></section>;
}
