import declarations from '../app/operations.json' with { type: 'json' };
export const PLAN_WRITE_KINDS = Object.freeze(declarations.planKinds);

export function friendlyError(error) {
  const code = String(error?.message ?? error).replace(/^Error invoking remote method '[^']+':\s*/, '').replace(/^(?:Error:\s*)+/,'');
  const [key, ...details] = code.split(':');
  const hints = {
    IMPORT_GIT_BASELINE_REQUIRED:'覆盖现有登记前需要可回滚的 Git 提交。请在仓库页提交计划涉及的现有配置，再重新预览；其它暂存内容不会混入。',
    IMPORT_EXTERNAL_CHANGE:'导入目标已被其它操作改动，已保留现场。请重新读取记录，不能用旧计划覆盖新内容。',
    IMPORT_BUSY:'这份导入仍在执行，请等待安全步骤收口或停止本次操作后再继续。',
    IMPORT_ALREADY_REVERTED:'这份导入已撤销。冻结版本保留；需要再采用时请生成新的版本选择计划。',
    IMPORT_PLATFORM_REQUIRED:'请选择已创建 bridge 的所属平台，本体、暂存与记录将归它的 runtime。',
    IMPORT_PLACEMENT_INVALID:'软件安置计划与本次来源或平台不一致，请重新识别并生成组合计划。',
    IMPORT_FOREIGN_REGISTRY_CHANGE:'这份导入试图同时修改其它资源登记，已停止；每次只修改当前资源。',
    IMPORT_MUTATION_NOT_ALLOWED:'导入计划包含不属于当前资源或平台的写入路径，已停止。',
    INTAKE_SOURCE_REQUIRED:'请选择已有文件、文件夹或 ZIP 作为本体来源。',
    INTAKE_SOURCE_MISSING:'来源已不存在，请重新选择；管理台不会创建假的本体。',
    INTAKE_LINK_NOT_ALLOWED:'来源包含符号链接或目录联接，无法保证读写边界。请改选普通目录或普通文件。',
    INTAKE_UNSAFE_PATH:'包内路径越界或不适合 Windows 文件名，已停止识别。原件保留，请修正压缩包。',
    INTAKE_DUPLICATE_PATH:'包内有重复或大小写冲突的路径，无法确定要接入哪一份。',
    INTAKE_SOURCE_CHANGED:'来源在预览后发生变化，请重新识别并核对计划；原件没有被覆盖。',
    INTAKE_TEXT_ENCODING:'正文需要先转换为 UTF-8（可含 BOM），管理台不会猜测编码后丢失文字。',
    INTAKE_ZIP_FILENAME_ENCODING:'ZIP 文件名编码无法确定，请用 UTF-8 文件名重新打包。',
    INTAKE_ZIP64_REQUIRED:'这份 ZIP 使用 ZIP64，请先解压为普通文件夹再选择；无需手工整理成三仓结构。',
    INTAKE_ZIP_INVALID:'压缩包结构不完整或不一致，请先确认能正常解压，再选择本体。',
    INTAKE_ZIP_CONTENT_MISMATCH:'压缩内容与清单校验不符，可能已损坏，已停止导入。',
    INTAKE_ZIP_ENCRYPTED:'这是加密 ZIP，请在本机解密后选择普通目录。密码不会写入导入计划。',
    INTAKE_SOURCE_EMPTY:'排除缓存和凭据后没有可接入文件，请选择实际本体。',
    INTAKE_ENTRY_INVALID:'请选择清单里可纳入的正文或程序入口；被排除文件不能作为入口。',
    RESOURCE_VERSION_CANDIDATE:'这个版本仍是开发候选，尚不能采用。请使用已发布版本，或等候选验证并发布后重新读取。',
    VERSION_PAIR_MISMATCH:'引擎与检查器没有按依赖锁配对，请选择完整推荐组合，不能只切其中一件。',
    TASK_CANCELLED:'已停止本次任务。已完成的安全步骤和证据保留，可重新扫描后继续。',
    CERTIFICATION_SCOPE_CHANGED:'确认后资源或配置发生了变化，请重新预览检查范围。',
    CERTIFICATION_EMPTY_SELECTION:'当前选择没有对应的启用资源，不能将空检查标为通过。',
    CERTIFICATION_BINDING_CHANGED:'检查期间资源或平台配置改变，本次结果不能用于认证。请重新读取后检查。',
    CERTIFICATION_PLATFORM_PATH_MISMATCH:'认证使用的配置或环境文件必须属于所选平台，不能借用其它平台。',
    RECOVERY_EXTERNAL_CHANGE: '失败恢复时发现文件又被外部修改。已保留现场和备份，不会用旧内容覆盖新改动；请查看恢复记录。',
    RESOURCE_SCHEMA_INVALID: '资源结构不符合架构契约，请查看字段问题并补齐后重新预览。',
    RESOURCE_IDENTITY_MISMATCH: '资源 manifest 的 ID 或版本与目标目录不一致，请更正候选文件。',
    WORKFLOW_IDENTITY_MISMATCH: '工作流定义与 manifest 的 ID 或版本不一致，请更正候选定义；已发布的旧版本不会被覆盖。',
    RELEASE_HASH_MISMATCH: '发布内容与封条哈希不一致，管理台已阻止采用这个版本。',
    RELEASE_FILE_SET_MISMATCH: '发布目录包含未封存或缺失的文件，不能采用或验证通过。',
    RELEASE_CHECKSUM_FORMAT: 'SHA256SUMS 不是可读的正式哈希清单，请重新发布合法新版本。',
    REGISTRY_SCHEMA_INVALID: '注册表结构不正确，不能用任意 JSON 替换架构登记。',
    RESOURCE_DEPENDENCY_NOT_PINNED: '依赖必须填写精确版本，不能填写 current、latest 或范围。',
    INVALID_REMOTE: '请选择这个仓库已经配置的远端名称，不能填写推送选项或不存在的远端。',
    GIT_ROLLBACK_DIRTY: '当前还有未提交或暂存的文件。请先提交或备份并处理这些改动，再生成回滚计划。',
    GIT_BACKUP_PLATFORM_REQUIRED: '历史备份需要选择一个已存在的平台作为备份归属。',
    GIT_BACKUP_ALREADY_EXISTS: '这个备份目录已经存在，请填写新的备份名称；管理台不会覆盖旧备份。',
    PUSH_BLOCKED_SENSITIVE: '即将推送的提交中发现凭据、本体或大文件，请处理后重新预览。',
    APPLICATION_CLOSING: '管理台正在停止本次任务并保存中止证据，请等待窗口关闭。',
    GIT_IDENTITY_REQUIRED: '请在接入向导的登记页填写 Git 提交姓名和邮箱，再点击预览一键接入／继续。这是提交署名，无需输入 GitHub 密码。',
    ONBOARDING_CANCELLED: '本次检查已停止，所属进程树已回收。已保存的配置和证据保留，可从向导继续。',
    RAW_SECRET_NOT_ALLOWED: '配置中只能填写凭据引用，不能填写密码或令牌原值。',
    DOCUMENT_BASELINE_MISMATCH: '文档在读取后发生了变化，请重新打开文档再编辑。',
    PLATFORM_CONFIGURATION_PATH_MISMATCH: '环境、证据和配置必须属于所选平台，请选择它自己的目录。',
    INVALID_PLATFORM_ID: '平台 ID 需为 2–31 位小写英文字母、数字或连字符，不能使用三仓等保留目录名。',
    PLAN_PAYLOAD_MISMATCH: '计划内容或版本已变化，请重新读取目标再生成计划。',
    PLATFORM_SCAFFOLD_CONFIRMATION_REQUIRED: '创建新平台目录前，请勾选目录创建确认。',
    CLIENT_ARGUMENTS_INVALID: '客户端参数需要逐项填写，不能输入任意拼接命令。',
    ONBOARDING_CONFIGURATION_REQUIRED: '请先保存完整配置，再准备运行环境。',
    RUNTIME_PYTHON_REQUIRED: '请选择能运行的 Python 3.10 或更新版本。',
    RUNTIME_BACKEND_REQUIRED: '请先检测并保存隔离后端，或选择本平台已有的后端配置。',
    RUNTIME_SEALED_BACKEND_REQUIRED: '当前步骤需要已就绪的 WSL 隔离后端。缺少系统组件时请先完成安装，再回到此处继续。',
    RUNTIME_PREPARATION_FAILED: '环境准备失败，原环境未切换。请查看下方原因，修复系统设施或下载连接后重新生成计划。',
    CLIENT_ADAPTER_PENDING: '这个客户端入口还没有可验证的适配器。可先安装标准 CLI 客户端；原生客户端接线会单独显示待完成。',
    CLIENT_ENTRY_DRIFT: '已安装的客户端入口文件发生了变化，请重新预览并安装入口。',
    CLIENT_RECEIPT_MISMATCH: '客户端回执与本次挑战、平台或版本不符，不能作为接入证据。',
    CLIENT_CONNECTION_FAILED: '客户端未完成真实连接，请查看客户端位置并重新测试。',
    ONBOARDING_RESUME_DRIFT: '上次接入中断后，配置或版本已改变。请重新预览接入计划；旧证据不会被静默沿用。',
    ONBOARDING_ALREADY_RUNNING: '该平台已有一次接入正在执行，请先等待或停止它。',
    ONBOARDING_NOT_VERIFIED: '检查、客户端回环或配置入库尚未完成，请先完成相应步骤。',
    GIT_UNRELATED_STAGED_FILES: 'Git 暂存区还有本轮之外的文件。请先处理它们，管理台不会将其混入接入提交。',
    ONBOARDING_CAPABILITY_PROBE_FAILED: '必要能力探针尚未通过，已停在当前步骤。请查看本平台的接入记录后修复并继续。',
    ONBOARDING_CHECK_FAILED: '接入认证尚未通过。请打开平台的检查问题或接入记录查看具体原因；已通过的安装与配置步骤保留。',
    EXTERNAL_CHANGE_DETECTED: '目标文件已被其他程序修改，管理台已阻止覆盖，请重新扫描。',
    TOP_LEVEL_CONFIRMATION_REQUIRED: '顶层治理文件需要勾选确认后才能生成计划。',
    TARGET_VERSION_UNAVAILABLE: '目标版本不在当前共享仓目录中，请先确认版本已发布。',
    POINTER_BASELINE_REQUIRED: '这个指针缺少基线哈希，请重新扫描工作区。',
    CATALOG_BASELINE_MISMATCH: 'registry 在读取后发生了变化，请重新扫描工作区。',
    CATALOG_ENTRY_ALREADY_EXISTS: '这个条目已经存在，请先查看现有条目。',
    CATALOG_ENTRY_NOT_FOUND: '没有找到这个条目。',
    CATALOG_CURRENT_NOT_FOUND: 'agent 的 current.json 不存在，不能注册。',
    SKILL_CATALOG_NOT_FOUND: '技能目录文件不存在，不能注册。',
    PLATFORM_PATH_OUTSIDE_WORKSPACE: '平台目录必须位于当前工作区内。',
    SOFTWARE_BODY_PATH_NOT_FOUND: '软件配方声明的本体路径不存在。',
    TRANSACTION_TARGET_OUTSIDE_WORKSPACE: '目标路径不在当前工作区内，操作已阻止。',
    TRANSACTION_KIND_UNSUPPORTED: '此类计划暂时只能查看，尚未提供安全执行器。',
    RESOURCE_REFERENCED: '仍有现行启用资源引用它，停用或移除已阻止。下方列出全部引用文件',
    NO_CHANGE: '目标版本与当前默认版本相同，无需切换。',
    TARGET_VERSION_NOT_FROZEN: '目标版本缺少发布封条 SHA256SUMS，不能切换。',
    SOFTWARE_CONNECTOR_NOT_CONFIGURED: '所选平台仍未绑定新版软件连接器，请换选已配置的平台或先完成平台接线。',
    INTEGRATION_BASELINE_MISMATCH: '目标在预览后已变化，请重新读取目标再生成计划。',
    DEFECT_BOOK_BASELINE_MISMATCH: '缺陷状态簿在读取后发生了变化，请刷新后再操作。',
    DEFECT_BOOK_NO_CHANGE: '该缺陷已经是这个状态，无需变更。',
    DEFECT_BOOK_ROW_NOT_FOUND: '没有找到这条缺陷，请刷新缺陷簿。',
    DEFECT_BOOK_ROW_EXISTS: '已存在同号缺陷，登记被阻止。',
    DEFECT_BOOK_FIELD_REQUIRED: '登记缺陷缺少必填字段。',
    DEFECT_BOOK_STATUS_INVALID: '非法的缺陷状态取值。',
    DEFECT_BOOK_CORRUPT: '缺陷状态簿不是合法 JSON，操作已阻止。',
    GIT_ADD_ALL_FORBIDDEN: '本工作区是白名单式仓库，只允许显式路径提交；. 、 -A 、通配符和绝对路径都被拒绝。',
    GIT_EXTERNAL_CHANGE: '计划生成后 HEAD 已变化（可能有新提交），计划已过期，请重新生成。',
    COMMIT_BLOCKED_SENSITIVE: '待提交文件命中敏感内容扫描，提交已阻止。',
    COMMIT_PATHS_REQUIRED: '请至少填写一个要提交的相对路径。',
    GIT_REPOSITORY_REQUIRED: '当前工作区不是 Git 仓库。',
    GIT_COMMAND_FAILED: 'Git 命令执行失败，见详情；未做任何自动恢复。',
    GIT_BACKUP_DESTINATION_INVALID: '备份目标必须位于 inbox/archive 之下。',
    INVALID_BRANCH_NAME: '分支名不合法。',
    INVALID_TAG_NAME: '标签名不合法。',
    RELEASE_VERSION_EXISTS: '目标版本目录已存在；已发布版本不可覆盖，请换一个 semver 版本号。',
    RELEASE_SEMVER_INVALID: '版本号必须是严格的 x.y.z。',
    RELEASE_RESOURCE_ID_INVALID: '资源 ID 不合法。',
    RELEASE_REPOSITORY_INVALID: '仓库只能是 tool 或 agent。',
    RESOURCE_NOT_FOUND: '找不到该资源目录或 current.json。',
    RELEASE_UPGRADE_SOURCE_MISSING: '升级来源版本目录不存在。',
    RELEASE_MANIFEST_VERSION_MISMATCH: 'manifest 版本与目标版本不一致，请重新生成计划。',
    CATALOG_SUPERSEDED_BY_REQUIRED: '标记 deprecated 必须提供 supersededBy。',
    SOFTWARE_NOT_DECLARED: '所选平台的连接器没有声明这个软件本体，先完成安置与绑定。',
    SOFTWARE_CONNECTOR_FAILED: '连接器进程执行失败，见审计事件；管理台不重试、不代答。',
    SOFTWARE_CONNECTOR_INVALID: '连接器输出不是合法 JSON，启动结果未知。',
    SOFTWARE_CONNECTOR_ENTRY_MISSING: '连接器入口文件不存在。',
    RELEASE_SEMVER_INVALID: '版本号必须是严格的 x.y.z。'
  };
  return hints[key] ? `${hints[key]}（${key}）${details.length ? `\n${details.join(':').trim()}` : ''}` : code;
}

