export const PLAN_WRITE_KINDS = [
  'document-edit',
  'defect-book-edit',
  'resource-pointer',
  'platform-view',
  'registry-edit',
  'integration-config',
  'integration-registry',
  'software-import',
  'software-recipe-publish',
  'software-revert',
  'git-commit',
  'git-branch',
  'git-tag',
  'git-push',
  'git-rollback',
  'git-backup',
  'release-publish',
  'software-launch'
];

export function friendlyError(error) {
  const code = String(error?.message ?? error);
  const [key, ...details] = code.split(':');
  const hints = {
    DOCUMENT_BASELINE_MISMATCH: '文档在读取后发生了变化，请重新打开文档再编辑。',
    EXTERNAL_CHANGE_DETECTED: '目标文件已被其他程序修改，管理台已阻止覆盖，请重新扫描。',
    TOP_LEVEL_CONFIRMATION_REQUIRED: '顶层治理文件需要勾选确认后才能生成计划。',
    TARGET_VERSION_UNAVAILABLE: '目标版本不在当前共享仓目录中，请先确认版本已发布。',
    POINTER_BASELINE_REQUIRED: '这个指针缺少基线哈希，请重新扫描工作区。',
    CATALOG_BASELINE_MISMATCH: 'registry 在读取后发生了变化，请重新扫描工作区。',
    CATALOG_ENTRY_ALREADY_EXISTS: '这个条目已经存在，请先查看现有条目。',
    CATALOG_ENTRY_NOT_FOUND: '没有找到这个条目。',
    CATALOG_CURRENT_NOT_FOUND: 'agent 的 current.json 不存在，不能注册。',
    SKILL_CATALOG_NOT_FOUND: '技能目录文件不存在，不能注册。',
    PLATFORM_PATH_OUTSIDE_WORKSPACE: '平台目录必须位于当前工作区内。',
    SOFTWARE_BODY_PATH_NOT_FOUND: '软件配方声明的本体路径不存在。',
    TRANSACTION_TARGET_OUTSIDE_WORKSPACE: '目标路径不在当前工作区内，操作已阻止。',
    TRANSACTION_KIND_UNSUPPORTED: '此类计划暂时只能查看，尚未提供安全执行器。',
    RESOURCE_REFERENCED: '仍有现行启用资源引用它，停用或移除已阻止。下方列出全部引用文件',
    NO_CHANGE: '目标版本与当前默认版本相同，无需切换。',
    TARGET_VERSION_NOT_FROZEN: '目标版本缺少发布封条 SHA256SUMS，不能切换。',
    SOFTWARE_CONNECTOR_NOT_CONFIGURED: '所选平台仍未绑定新版软件连接器，请换选已配置的平台或先完成平台接线。',
    INTEGRATION_BASELINE_MISMATCH: '目标在预览后已变化，请重新读取目标再生成计划。',
    DEFECT_BOOK_BASELINE_MISMATCH: '缺陷状态簿在读取后发生了变化，请刷新后再操作。',
    DEFECT_BOOK_NO_CHANGE: '该缺陷已经是这个状态，无需变更。',
    DEFECT_BOOK_ROW_NOT_FOUND: '没有找到这条缺陷，请刷新缺陷簿。',
    DEFECT_BOOK_ROW_EXISTS: '已存在同号缺陷，登记被阻止。',
    DEFECT_BOOK_FIELD_REQUIRED: '登记缺陷缺少必填字段。',
    DEFECT_BOOK_STATUS_INVALID: '非法的缺陷状态取值。',
    DEFECT_BOOK_CORRUPT: '缺陷状态簿不是合法 JSON，操作已阻止。',
    GIT_ADD_ALL_FORBIDDEN: '本工作区是白名单式仓库，只允许显式路径提交；. 、 -A 、通配符和绝对路径都被拒绝。',
    GIT_EXTERNAL_CHANGE: '计划生成后 HEAD 已变化（可能有新提交），计划已过期，请重新生成。',
    COMMIT_BLOCKED_SENSITIVE: '待提交文件命中敏感内容扫描，提交已阻止。',
    COMMIT_PATHS_REQUIRED: '请至少填写一个要提交的相对路径。',
    GIT_REPOSITORY_REQUIRED: '当前工作区不是 Git 仓库。',
    GIT_COMMAND_FAILED: 'Git 命令执行失败，见详情；未做任何自动恢复。',
    GIT_BACKUP_DESTINATION_INVALID: '备份目标必须位于 inbox/archive 之下。',
    INVALID_BRANCH_NAME: '分支名不合法。',
    INVALID_TAG_NAME: '标签名不合法。',
    RELEASE_VERSION_EXISTS: '目标版本目录已存在；已发布版本不可覆盖，请换一个 semver 版本号。',
    RELEASE_SEMVER_INVALID: '版本号必须是严格的 x.y.z。',
    RELEASE_RESOURCE_ID_INVALID: '资源 ID 不合法。',
    RELEASE_REPOSITORY_INVALID: '仓库只能是 tool 或 agent。',
    RESOURCE_NOT_FOUND: '找不到该资源目录或 current.json。',
    RELEASE_UPGRADE_SOURCE_MISSING: '升级来源版本目录不存在。',
    RELEASE_MANIFEST_VERSION_MISMATCH: 'manifest 版本与目标版本不一致，请重新生成计划。',
    CATALOG_SUPERSEDED_BY_REQUIRED: '标记 deprecated 必须提供 supersededBy。',
    SOFTWARE_NOT_DECLARED: '所选平台的连接器没有声明这个软件本体，先完成安置与绑定。',
    SOFTWARE_CONNECTOR_FAILED: '连接器进程执行失败，见审计事件；管理台不重试、不代答。',
    SOFTWARE_CONNECTOR_INVALID: '连接器输出不是合法 JSON，启动结果未知。',
    SOFTWARE_CONNECTOR_ENTRY_MISSING: '连接器入口文件不存在。',
    RELEASE_SEMVER_INVALID: '版本号必须是严格的 x.y.z。'
  };
  return hints[key] ? `${hints[key]}（${key}）${details.length ? `\n${details.join(':').trim()}` : ''}` : code;
}

